blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://discord.com/invite/Bw5JYMV9
    about: Reach out to us on discord or our github discussions page.
  - name: 📞 Dedicated Support
    url: https://mail.google.com/mail/u/0/?view=cm&fs=1&to=support@ga-universe.com&tf=1
    about: Need personalized assistance? Reach out to us for dedicated support with GA_Universe
